version: "3.8"

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: demo
    ports:
      - "8000:8000"
      - "7860:7860"
    depends_on:
      - qdrant
    volumes:
      - /home/ubuntu/KINGO-BOT-PLUS:/app
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
