FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install fastapi uvicorn gradio requests qdrant-client sentence-transformers openai

EXPOSE 8000 7860

CMD ["bash", "-c", "uvicorn app:app --host 0.0.0.0 --port 8000 & python demo.py"]
